### ISSUE TITLE
Migrate from Gitbook to Github gh-pages

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion-sprints#57]
We can use Github to edit markdown files in `gh-pages`. Every change will cause Github to publish the contents on github.io

# Advantages
Github is less buggy than Gitbook.

# Same
Both tools provide a online markdown editor.

# Disadvantages
Github does not have a multi-user online markdown editor.

**Comment by jverkoey** [comment]
Done. https://material-motion.github.io/material-motion/
